---
title: "Chronic Pain"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Resources

- [Curable](https://apps.apple.com/us/app/curable/id1325784379)
- [Explain Pain Second Edition by David S. Butler & G. Lorimer Moseley](https://www.noigroup.com/product/explain-pain-second-edition/)
- [TMS Wiki](https://www.tmswiki.org)
- [My TMS Journey](https://mytmsjourney.com)
  - [Recovery Roadmap](https://mytmsjourney.com/recovery-journey-roadmap/)
- [Coursera Course: Reign of Pain](https://www.coursera.org/learn/reign-of-pain/)
- [Neuroplastic Transformation Workbook](https://www.integrativepain.com/general-7)

***

## Core of healing neuroplastic chronic pain

The first step is to have a deep understanding of the brain origin of pain, and believe that we can recover from chronic pain and get our life back by training our brain.  

Most of us don’t realize it, but we are actually training our brains every time we learn a new skill, such as reading, typing, singing a song, learning a dance or riding a bike. It is through repetition, practice, creativity and improvement that we master any activity. **This happens through electrical and chemical signals in our cells creating pathways in our brains that allow us to perform these tasks.** We are literally changing the anatomy of our brains. By being aware of this process we can consciously utilize it to our benefit.

### Three rules of neuroplasticity

There are three basic rules of neuroplasticity:

1. What is fired is wired.

2. What you don’t use you lose.

3. When you make them you break them; when you break them you make them.

These principles are the reason our brains change with repetitive stimulation.

*Excerpt From Neuroplastic Transformation by Michael H. Moskowitz*