---
title: "Mindfulness"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Resources
## Courses
- MasterClass: [Jon Kabat-Zinn Teaches Mindfulness and Meditation](https://www.masterclass.com/classes/jon-kabat-zinn-teaches-mindfulness-and-meditation)
- [Course](https://www.bilibili.com/video/BV19y4y1V7RU?p=8&spm_id_from=pageDriver&vd_source=ff576ca272bc04d6aa7b61ccc010e0c5)

## Books
- [The Mindful Path to Self-Compassion: Freeing Yourself from Destructive Thoughts and Emotions](https://www.amazon.com/Mindful-Path-Self-Compassion-Yourself-Destructive/dp/1593859759)

## Websites and Apps
- [Insight Timer](https://apps.apple.com/us/app/insight-timer-meditate-sleep/id337472899)
- For chronic pain patients: 
  - [Curable](https://apps.apple.com/us/app/curable/id1325784379)
  - [TMS Wiki](https://www.tmswiki.org)
  - [My TMS Journey](https://mytmsjourney.com)
    - [Recovery Roadmap](https://mytmsjourney.com/recovery-journey-roadmap/)

# Meditation
Don't think about how to do it all right! Whatever arises. Everything arises is part of the actuality of experience in this moment.

I am already perfect exactly as I am. I am OK just as I am. Start with being present as I am.

The challenge of meditation is not about attaining anything. It's about recognizing that I am already **WHOLE** just as I am.

Compassion, self-compassion and kindness are absolutely woven into how you take your seat, how you are in relationship to this breath coming in, and to whatever arises in the field of the mind, in the field of the heart, in the field of the body, or in the field of the world that requires some kind of meeting, response, appropriate recognition in the moment. 

### Poem: The Guest House  
by Jalaluddin Rumi

This being human is a guest house.  
Every morning a new arrival.

A joy, a depression, a meanness,  
some momentary awareness comes  
as an unexpected visitor.

Welcome and entertain them all!  
Even if they’re a crowd of sorrows,  
who violently sweep your house  
empty of its furniture,  
still, treat each guest honorably.  
He may be clearing you out  
for some new delight.

The dark thought, the shame, the malice,  
meet them at the door laughing,  
and invite them in.  

Be grateful for whoever comes,  
because each has been sent  
as a guide from beyond.

# Exercise

How to lose weight?

